// ─── Curated Anime Character Traits Database ─────────────────
// Structured trait lookup for 150+ popular anime characters.
// Used as the highest-priority data source in the parse pipeline.

export interface AnimeTraits {
  hairColor: string;
  hairStyle: string;
  eyeColor: string;
  gender: string;
  age: string;
  role: string;
  personality: string;
  coreTheme: string;
  accent: string;
  wardrobeDetails: string;
  keyProp: string;
  alias: string;
}

// Each key is a lowercase search token that will be substring-matched
const TRAITS_DB: Record<string, AnimeTraits> = {
  // ── NARUTO ──────────────────────────────────────────────────
  "naruto uzumaki": { hairColor: "golden blonde", hairStyle: "spiky", eyeColor: "blue", gender: "Male", age: "Teenager (17)", role: "Ninja / Shinobi", personality: "Energetic, Determined, Kind", coreTheme: "Ninja / Shinobi World", accent: "Loud, informal, energetic", wardrobeDetails: "orange and black jumpsuit, forehead protector, ninja sandals", keyProp: "Rasengan — spinning chakra sphere technique", alias: "Nine-Tails Jinchuuriki" },
  "sasuke uchiha": { hairColor: "jet black", hairStyle: "spiky", eyeColor: "dark / red (Sharingan)", gender: "Male", age: "Teenager (17)", role: "Ninja / Shinobi", personality: "Cold, Ambitious, Analytical", coreTheme: "Ninja / Shinobi World", accent: "Gruff, low-pitched, brief", wardrobeDetails: "high-collared dark blue tunic, white arm guards, rope belt", keyProp: "Kusanagi Sword — lightning-infused katana", alias: "The Last Uchiha" },
  "sakura haruno": { hairColor: "sakura pink", hairStyle: "short", eyeColor: "green", gender: "Female", age: "Teenager (17)", role: "Medic / Healer", personality: "Determined, Caring, Hot-headed", coreTheme: "Ninja / Shinobi World", accent: "Assertive, emotional, direct", wardrobeDetails: "red qipao top, black shorts, medical ninja gloves, forehead protector", keyProp: "Chakra-enhanced fists — superhuman strength punches", alias: "Tsunade's Apprentice" },
  "kakashi hatake": { hairColor: "platinum silver", hairStyle: "spiky tilted", eyeColor: "dark / red (Sharingan)", gender: "Male", age: "Young Adult (29)", role: "Ninja / Shinobi", personality: "Calm, Wise, Laid-back", coreTheme: "Ninja / Shinobi World", accent: "Calm, measured, occasionally witty", wardrobeDetails: "standard jonin vest, navy blue outfit, face mask, tilted forehead protector", keyProp: "Icha Icha Paradise novel — always reading", alias: "Copy Ninja Kakashi" },
  "hinata hyuga": { hairColor: "dark indigo", hairStyle: "long straight", eyeColor: "lavender (Byakugan)", gender: "Female", age: "Teenager (16)", role: "Ninja / Shinobi", personality: "Shy, Gentle, Determined", coreTheme: "Ninja / Shinobi World", accent: "Soft-spoken, hesitant, polite", wardrobeDetails: "lavender and cream hooded jacket, dark navy pants, sandals", keyProp: "Byakugan — all-seeing white eye technique", alias: "Byakugan Princess" },
  "itachi uchiha": { hairColor: "jet black", hairStyle: "long ponytail", eyeColor: "red (Mangekyo Sharingan)", gender: "Male", age: "Young Adult (21)", role: "Ninja / Shinobi", personality: "Calm, Mysterious, Self-sacrificing", coreTheme: "Ninja / Shinobi World", accent: "Quiet, measured, philosophical", wardrobeDetails: "black Akatsuki cloak with red clouds, mesh armor underneath, forehead protector with slash", keyProp: "Totsuka Blade — ethereal sealing sword", alias: "Clan Killer Itachi" },
  "gaara": { hairColor: "crimson red", hairStyle: "short messy", eyeColor: "teal green", gender: "Male", age: "Teenager (16)", role: "Ninja / Shinobi", personality: "Stoic, Lonely, Protective", coreTheme: "Ninja / Shinobi World", accent: "Low, monotone, intense", wardrobeDetails: "dark red coat, sand gourd strapped to back, dark pants", keyProp: "Sand Gourd — container of his sand weapon", alias: "Gaara of the Sand" },
  "rock lee": { hairColor: "jet black", hairStyle: "bowl cut", eyeColor: "dark", gender: "Male", age: "Teenager (17)", role: "Ninja / Shinobi", personality: "Energetic, Determined, Honorable", coreTheme: "Ninja / Shinobi World", accent: "Loud, passionate, dramatic", wardrobeDetails: "green spandex jumpsuit, orange leg warmers, bandaged arms", keyProp: "Training Weights — heavy ankle weights for speed training", alias: "The Green Beast of Konoha" },
  "jiraiya": { hairColor: "white", hairStyle: "long spiky", eyeColor: "dark", gender: "Male", age: "Prime Adult (50)", role: "Ninja / Shinobi", personality: "Wise, Perverted, Loyal", coreTheme: "Ninja / Shinobi World", accent: "Boisterous, theatrical, warm", wardrobeDetails: "red kabuki vest, green short kimono, mesh armor, wooden sandals, horned forehead protector", keyProp: "Summoning Scroll — toad summoning contract", alias: "The Toad Sage" },

  // ── ONE PIECE ────────────────────────────────────────────────
  "monkey d. luffy": { hairColor: "jet black", hairStyle: "short messy", eyeColor: "dark brown", gender: "Male", age: "Young Adult (19)", role: "Pirate", personality: "Cheerful, Reckless, Loyal", coreTheme: "Pirate / Nautical Adventure", accent: "Informal, energetic, loud", wardrobeDetails: "red vest, blue denim shorts, straw sandals", keyProp: "Straw Hat — treasured hat given by Shanks", alias: "Straw Hat Luffy" },
  "roronoa zoro": { hairColor: "emerald green", hairStyle: "short cropped", eyeColor: "dark", gender: "Male", age: "Young Adult (21)", role: "Swordsman / Samurai", personality: "Stoic, Disciplined, Loyal", coreTheme: "Pirate / Nautical Adventure", accent: "Gruff, blunt, few words", wardrobeDetails: "green haramaki sash, dark green haori robes, three gold earrings, combat boots", keyProp: "Three Swords — including Wado Ichimonji katana", alias: "Pirate Hunter Zoro" },
  "nami": { hairColor: "fiery orange", hairStyle: "long wavy", eyeColor: "brown", gender: "Female", age: "Young Adult (20)", role: "Pirate", personality: "Sharp, Greedy, Caring", coreTheme: "Pirate / Nautical Adventure", accent: "Assertive, commanding, sometimes sweet", wardrobeDetails: "bikini top, fitted jeans, high heels, log pose on wrist", keyProp: "Clima-Tact — weather-manipulating staff", alias: "Cat Burglar Nami" },
  "sanji": { hairColor: "golden blonde", hairStyle: "parted (covers one eye)", eyeColor: "blue", gender: "Male", age: "Young Adult (21)", role: "Pirate", personality: "Chivalrous, Hot-headed, Caring", coreTheme: "Pirate / Nautical Adventure", accent: "Smooth, flirtatious with women, aggressive with men", wardrobeDetails: "black double-breasted suit, blue dress shirt, black tie, dress shoes", keyProp: "Lighter — always smoking a cigarette", alias: "Black Leg Sanji" },
  "nico robin": { hairColor: "jet black", hairStyle: "long straight", eyeColor: "blue", gender: "Female", age: "Young Adult (28)", role: "Pirate", personality: "Calm, Intellectual, Dark humor", coreTheme: "Pirate / Nautical Adventure", accent: "Calm, composed, occasionally morbid", wardrobeDetails: "purple leather jacket, long skirt, sunglasses on head, cowboy hat", keyProp: "Hana Hana no Mi — power to sprout body parts", alias: "Devil Child Robin" },
  "portgas d. ace": { hairColor: "jet black", hairStyle: "wavy", eyeColor: "dark", gender: "Male", age: "Young Adult (20)", role: "Pirate", personality: "Loyal, Hot-headed, Protective", coreTheme: "Pirate / Nautical Adventure", accent: "Casual, warm, passionate", wardrobeDetails: "shirtless, orange cowboy hat, beaded necklace, black shorts, boots", keyProp: "Mera Mera no Mi — fire-producing power", alias: "Fire Fist Ace" },
  "shanks": { hairColor: "crimson red", hairStyle: "medium messy", eyeColor: "dark", gender: "Male", age: "Prime Adult (39)", role: "Pirate", personality: "Charismatic, Wise, Powerful", coreTheme: "Pirate / Nautical Adventure", accent: "Relaxed, commanding when serious", wardrobeDetails: "white shirt, black cape draped over shoulders, brown pants, three scars over left eye", keyProp: "Gryphon Sword — single-edged saber", alias: "Red-Haired Shanks" },
  "trafalgar law": { hairColor: "jet black", hairStyle: "short messy", eyeColor: "grey", gender: "Male", age: "Young Adult (26)", role: "Pirate", personality: "Calm, Cunning, Strategic", coreTheme: "Pirate / Nautical Adventure", accent: "Cool, collected, sardonic", wardrobeDetails: "spotted fur hat, yellow hoodie, dark jeans, tribal arm tattoos", keyProp: "Kikoku — cursed nodachi sword", alias: "Surgeon of Death" },

  // ── DRAGON BALL ──────────────────────────────────────────────
  "son goku": { hairColor: "jet black", hairStyle: "wild spiky", eyeColor: "dark", gender: "Male", age: "Prime Adult (40)", role: "Vanguard Warrior", personality: "Cheerful, Naive, Determined", coreTheme: "Classic Shounen Fantasy", accent: "Informal, friendly, childlike", wardrobeDetails: "orange and blue gi, blue undershirt, blue wristbands, blue boots", keyProp: "Power Pole — extending red staff", alias: "Kakarot" },
  "vegeta": { hairColor: "jet black", hairStyle: "upward spiky (flame-shaped)", eyeColor: "dark", gender: "Male", age: "Prime Adult (42)", role: "Vanguard Warrior", personality: "Arrogant, Prideful, Determined", coreTheme: "Classic Shounen Fantasy", accent: "Cocky, condescending, intense", wardrobeDetails: "white and blue Saiyan armor, blue jumpsuit, white gloves and boots", keyProp: "Scouter — power-level measuring device", alias: "Prince of All Saiyans" },
  "gohan": { hairColor: "jet black", hairStyle: "short messy", eyeColor: "dark", gender: "Male", age: "Teenager (16)", role: "Student", personality: "Kind, Brave, Studious", coreTheme: "Classic Shounen Fantasy", accent: "Polite, gentle, occasionally fierce", wardrobeDetails: "purple gi with red sash, or school uniform and glasses", keyProp: "Z Sword — legendary mystic blade", alias: "The Great Saiyaman" },
  "piccolo": { hairColor: "none (bald)", hairStyle: "bald", eyeColor: "dark", gender: "Male", age: "Ancient Immortal (100+)", role: "Vanguard Warrior", personality: "Stoic, Wise, Protective", coreTheme: "Classic Shounen Fantasy", accent: "Deep, stern, authoritative", wardrobeDetails: "purple gi, white cape and turban, weighted training clothes, green skin, antennae", keyProp: "Special Beam Cannon — concentrated energy beam", alias: "The Namekian" },
  "frieza": { hairColor: "none (bald)", hairStyle: "bald", eyeColor: "red", gender: "Male", age: "Ancient Immortal (100+)", role: "Royalty", personality: "Cruel, Arrogant, Calculating", coreTheme: "Classic Shounen Fantasy", accent: "Elegant, refined, menacing", wardrobeDetails: "white and purple bio-armor, purple tail, horns, pink skin markings", keyProp: "Death Beam — precision finger beam", alias: "Emperor of the Universe" },
  "trunks": { hairColor: "lavender purple", hairStyle: "straight shoulder-length", eyeColor: "blue", gender: "Male", age: "Teenager (17)", role: "Vanguard Warrior", personality: "Brave, Serious, Compassionate", coreTheme: "Classic Shounen Fantasy", accent: "Respectful, serious, determined", wardrobeDetails: "blue Capsule Corp jacket, black tank top, grey pants, boots, leather sword sheath", keyProp: "Brave Sword — inherited broadsword", alias: "Future Trunks" },
  "bulma": { hairColor: "turquoise blue", hairStyle: "short bob", eyeColor: "blue", gender: "Female", age: "Prime Adult (38)", role: "Scientist / Researcher", personality: "Intelligent, Bossy, Adventurous", coreTheme: "Classic Shounen Fantasy", accent: "Confident, sassy, commanding", wardrobeDetails: "various fashionable outfits, lab coat when working, Capsule Corp accessories", keyProp: "Dragon Radar — device to locate Dragon Balls", alias: "The Genius Inventor" },

  // ── ATTACK ON TITAN ─────────────────────────────────────────
  "eren yeager": { hairColor: "dark brown", hairStyle: "medium messy", eyeColor: "teal green", gender: "Male", age: "Teenager (15)", role: "Survey Corps Soldier", personality: "Determined, Hot-headed, Vengeful", coreTheme: "Military / War Drama", accent: "Passionate, angry, intense", wardrobeDetails: "brown Survey Corps jacket, white pants, ODM gear harness, green cloak", keyProp: "ODM Gear — omni-directional mobility equipment with dual blades", alias: "Attack Titan" },
  "mikasa ackerman": { hairColor: "jet black", hairStyle: "short bob", eyeColor: "dark grey", gender: "Female", age: "Teenager (15)", role: "Survey Corps Soldier", personality: "Loyal, Protective, Stoic", coreTheme: "Military / War Drama", accent: "Quiet, firm, emotionally reserved", wardrobeDetails: "brown Survey Corps jacket, white pants, red scarf, ODM gear harness", keyProp: "Dual Thunder Spears — anti-titan blades", alias: "Humanity's Strongest Female Soldier" },
  "levi ackerman": { hairColor: "jet black", hairStyle: "undercut", eyeColor: "steel grey", gender: "Male", age: "Prime Adult (30)", role: "Survey Corps Soldier", personality: "Stoic, Blunt, Disciplined", coreTheme: "Military / War Drama", accent: "Cold, clipped, sarcastic", wardrobeDetails: "Survey Corps green cloak, white cravat, brown jacket, ODM gear", keyProp: "Dual reverse-grip blades — signature combat style", alias: "Humanity's Strongest Soldier" },
  "armin arlert": { hairColor: "golden blonde", hairStyle: "medium bob", eyeColor: "blue", gender: "Male", age: "Teenager (15)", role: "Survey Corps Soldier", personality: "Intelligent, Timid, Strategic", coreTheme: "Military / War Drama", accent: "Soft, thoughtful, articulate", wardrobeDetails: "brown Survey Corps jacket, white pants, green cloak", keyProp: "Strategic mind — tactical genius", alias: "Colossal Titan" },
  "erwin smith": { hairColor: "golden blonde", hairStyle: "neat parted", eyeColor: "blue", gender: "Male", age: "Prime Adult (35)", role: "Military Commander", personality: "Charismatic, Strategic, Selfless", coreTheme: "Military / War Drama", accent: "Commanding, inspiring, authoritative", wardrobeDetails: "Survey Corps commander coat, bolo tie, brown boots", keyProp: "Survey Corps commander's bolo tie", alias: "Commander Erwin" },

  // ── DEATH NOTE ───────────────────────────────────────────────
  "light yagami": { hairColor: "chestnut brown", hairStyle: "neat straight", eyeColor: "brown / red (Kira)", gender: "Male", age: "Teenager (17)", role: "Student", personality: "Intelligent, Arrogant, Manipulative", coreTheme: "Psychological Thriller", accent: "Polite, articulate, calculating", wardrobeDetails: "tan school blazer, white dress shirt, red necktie, pressed pants", keyProp: "Death Note — supernatural notebook that kills", alias: "Kira" },
  "l lawliet": { hairColor: "jet black", hairStyle: "messy unkempt", eyeColor: "dark", gender: "Male", age: "Young Adult (25)", role: "Detective", personality: "Analytical, Eccentric, Reserved", coreTheme: "Psychological Thriller", accent: "Deadpan, monotone, thoughtful", wardrobeDetails: "oversized white long-sleeve shirt, blue jeans, barefoot, hunched posture", keyProp: "Sweets Tray — always eating cake and sugar cubes", alias: "L / Ryuzaki" },
  "misa amane": { hairColor: "golden blonde", hairStyle: "twin tails", eyeColor: "brown / red (Shinigami Eyes)", gender: "Female", age: "Young Adult (19)", role: "Student", personality: "Cheerful, Obsessive, Naive", coreTheme: "Psychological Thriller", accent: "Bubbly, dramatic, idol-like", wardrobeDetails: "gothic lolita black dress, cross necklace, platform boots, lace accessories", keyProp: "Shinigami Eyes — ability to see lifespans", alias: "The Second Kira" },

  // ── DEMON SLAYER ─────────────────────────────────────────────
  "tanjiro kamado": { hairColor: "dark burgundy red", hairStyle: "short messy", eyeColor: "dark red", gender: "Male", age: "Teenager (15)", role: "Demon Slayer", personality: "Kind, Determined, Compassionate", coreTheme: "Classic Shounen Fantasy", accent: "Polite, earnest, empathetic", wardrobeDetails: "green and black checkered haori, black uniform, white leg wraps, hanafuda earrings", keyProp: "Nichirin Sword — color-changing demon-slaying blade", alias: "The Boy with Hanafuda Earrings" },
  "nezuko kamado": { hairColor: "jet black (orange tips)", hairStyle: "long flowing", eyeColor: "pink", gender: "Female", age: "Teenager (14)", role: "Demon Slayer", personality: "Protective, Gentle, Fierce (demon form)", coreTheme: "Classic Shounen Fantasy", accent: "Nonverbal (bamboo muzzle), expressive through actions", wardrobeDetails: "pink kimono with hemp leaf pattern, dark brown hair ribbon, bamboo muzzle", keyProp: "Bamboo Muzzle — restraint worn over mouth", alias: "The Demon Girl" },
  "zenitsu agatsuma": { hairColor: "golden blonde", hairStyle: "medium messy", eyeColor: "amber", gender: "Male", age: "Teenager (16)", role: "Demon Slayer", personality: "Cowardly, Loyal, Powerful (when asleep)", coreTheme: "Classic Shounen Fantasy", accent: "Whiny, panicked, dramatic crying", wardrobeDetails: "yellow and orange gradient haori, black uniform, standard demon slayer outfit", keyProp: "Nichirin Sword — thunder-breathing katana", alias: "Thunder Breathing Swordsman" },
  "inosuke hashibira": { hairColor: "dark blue (indigo)", hairStyle: "long wild", eyeColor: "green", gender: "Male", age: "Teenager (15)", role: "Demon Slayer", personality: "Wild, Aggressive, Competitive", coreTheme: "Classic Shounen Fantasy", accent: "Rough, shouting, challenging everyone", wardrobeDetails: "boar head mask, shirtless with muscular build, baggy pants, fur cuffs", keyProp: "Dual Chipped Nichirin Swords — serrated blades", alias: "King of the Mountains" },
  "kyojuro rengoku": { hairColor: "flame orange-red", hairStyle: "long flowing (flame-shaped)", eyeColor: "gold", gender: "Male", age: "Young Adult (20)", role: "Demon Slayer", personality: "Passionate, Honorable, Cheerful", coreTheme: "Classic Shounen Fantasy", accent: "Loud, enthusiastic, encouraging", wardrobeDetails: "white and red flame-patterned haori, Demon Slayer Corps uniform, flame cape", keyProp: "Flame Nichirin Sword — fire-breathing katana", alias: "Flame Hashira" },
  "giyu tomioka": { hairColor: "jet black", hairStyle: "ponytail", eyeColor: "dark blue", gender: "Male", age: "Young Adult (21)", role: "Demon Slayer", personality: "Stoic, Reserved, Lonely", coreTheme: "Classic Shounen Fantasy", accent: "Quiet, emotionless, terse", wardrobeDetails: "half-and-half haori (red/green pattern), Demon Slayer uniform, blue guard katana", keyProp: "Water Nichirin Sword — water-breathing katana", alias: "Water Hashira" },
  "shinobu kocho": { hairColor: "dark purple (butterfly gradient)", hairStyle: "butterfly clip bob", eyeColor: "purple", gender: "Female", age: "Young Adult (18)", role: "Demon Slayer", personality: "Cheerful, Sadistic, Intelligent", coreTheme: "Classic Shounen Fantasy", accent: "Soft, sweet, deceptively calm", wardrobeDetails: "butterfly-patterned haori, Demon Slayer uniform, butterfly hair ornament", keyProp: "Poison Nichirin Sword — wisteria poison-infused blade", alias: "Insect Hashira" },

  // ── MY HERO ACADEMIA ────────────────────────────────────────
  "izuku midoriya": { hairColor: "dark green", hairStyle: "messy curly", eyeColor: "green", gender: "Male", age: "Teenager (16)", role: "Pro Hero", personality: "Determined, Kind, Analytical", coreTheme: "Classic Shounen Fantasy", accent: "Nervous, mumbling, passionate when inspired", wardrobeDetails: "green hero costume with mask, white gloves, red boots, utility belt", keyProp: "One For All — inherited superpower passed down through generations", alias: "Deku" },
  "katsuki bakugo": { hairColor: "ash blonde", hairStyle: "spiky explosive", eyeColor: "red", gender: "Male", age: "Teenager (16)", role: "Pro Hero", personality: "Aggressive, Competitive, Prideful", coreTheme: "Classic Shounen Fantasy", accent: "Loud, angry, aggressive yelling", wardrobeDetails: "black tank top, grenade-like bracers, baggy pants, combat boots", keyProp: "Grenade Bracers — nitroglycerin sweat-powered explosions", alias: "Great Explosion Murder God Dynamight" },
  "shoto todoroki": { hairColor: "half white / half red", hairStyle: "straight medium", eyeColor: "turquoise (left) / grey (right)", gender: "Male", age: "Teenager (16)", role: "Pro Hero", personality: "Calm, Reserved, Conflicted", coreTheme: "Classic Shounen Fantasy", accent: "Monotone, calm, blunt", wardrobeDetails: "dark blue hero costume, ice on right side, fire on left, burn scar over left eye", keyProp: "Half-Cold Half-Hot — ice and fire dual quirk", alias: "Shoto" },
  "all might": { hairColor: "golden blonde", hairStyle: "twin antenna bangs", eyeColor: "blue", gender: "Male", age: "Prime Adult (49)", role: "Pro Hero", personality: "Heroic, Inspiring, Self-sacrificing", coreTheme: "Classic Shounen Fantasy", accent: "Booming, encouraging, 'I AM HERE!'", wardrobeDetails: "red, white, and blue hero costume, massive muscular build, cape", keyProp: "One For All — supreme power of justice", alias: "Symbol of Peace" },

  // ── FULLMETAL ALCHEMIST ──────────────────────────────────────
  "edward elric": { hairColor: "golden blonde", hairStyle: "braided ponytail", eyeColor: "gold", gender: "Male", age: "Teenager (15)", role: "Alchemist", personality: "Hot-headed, Determined, Compassionate", coreTheme: "Steampunk Adventure", accent: "Loud, argumentative, especially about height", wardrobeDetails: "red hooded coat, black leather pants, automail right arm and left leg", keyProp: "Automail Arm — mechanical prosthetic for alchemy", alias: "Fullmetal Alchemist" },
  "alphonse elric": { hairColor: "golden blonde", hairStyle: "short", eyeColor: "gold", gender: "Male", age: "Teenager (14)", role: "Alchemist", personality: "Kind, Gentle, Patient", coreTheme: "Steampunk Adventure", accent: "Soft, polite, youthful", wardrobeDetails: "massive suit of medieval armor (soul bound), hollow interior, glowing red eyes", keyProp: "Suit of Armor — his entire body is a steel shell", alias: "The Armored Alchemist" },
  "roy mustang": { hairColor: "jet black", hairStyle: "neat short", eyeColor: "dark", gender: "Male", age: "Young Adult (29)", role: "Military Commander", personality: "Ambitious, Charismatic, Strategic", coreTheme: "Military / War Drama", accent: "Confident, commanding, sometimes sarcastic", wardrobeDetails: "blue military uniform, white gloves with transmutation circles, black boots", keyProp: "Ignition Gloves — flame alchemy transmutation circles", alias: "Flame Alchemist" },
  "riza hawkeye": { hairColor: "golden blonde", hairStyle: "pinned up / clip", eyeColor: "amber", gender: "Female", age: "Young Adult (27)", role: "Military Commander", personality: "Disciplined, Loyal, Calm", coreTheme: "Military / War Drama", accent: "Professional, calm under pressure", wardrobeDetails: "blue military uniform, gun holsters, hair clip holding blonde hair up", keyProp: "Custom Handguns — dual semi-automatic pistols", alias: "Hawk's Eye" },
  "winry rockbell": { hairColor: "golden blonde", hairStyle: "long ponytail", eyeColor: "blue", gender: "Female", age: "Teenager (15)", role: "Mechanic / Engineer", personality: "Cheerful, Determined, Emotional", coreTheme: "Steampunk Adventure", accent: "Energetic, passionate about mechanics", wardrobeDetails: "tube top, overalls, work gloves, bandana, tool belt", keyProp: "Wrench — her signature engineering tool", alias: "The Automail Mechanic" },

  // ── JUJUTSU KAISEN ──────────────────────────────────────────
  "gojo satoru": { hairColor: "pure white", hairStyle: "spiky upswept", eyeColor: "bright blue (Six Eyes)", gender: "Male", age: "Young Adult (28)", role: "Jujutsu Sorcerer", personality: "Playful, Arrogant, Powerful", coreTheme: "Urban Supernatural / Magic Realism", accent: "Cocky, playful, taunting", wardrobeDetails: "dark navy high-collar uniform, black blindfold, white sneakers", keyProp: "Infinity — limitless cursed technique barrier", alias: "The Strongest Jujutsu Sorcerer" },
  "itadori yuji": { hairColor: "pink (dyed)", hairStyle: "short spiky", eyeColor: "brown", gender: "Male", age: "Teenager (15)", role: "Jujutsu Sorcerer", personality: "Kind, Athletic, Brave", coreTheme: "Urban Supernatural / Magic Realism", accent: "Casual, upbeat, straightforward", wardrobeDetails: "red hoodie, or Jujutsu High uniform, athletic build", keyProp: "Sukuna's Fingers — cursed objects he must consume", alias: "Sukuna's Vessel" },
  "megumi fushiguro": { hairColor: "dark navy", hairStyle: "spiky", eyeColor: "dark green", gender: "Male", age: "Teenager (15)", role: "Jujutsu Sorcerer", personality: "Serious, Reserved, Righteous", coreTheme: "Urban Supernatural / Magic Realism", accent: "Calm, measured, occasionally blunt", wardrobeDetails: "Jujutsu High dark uniform, stoic expression, lean build", keyProp: "Ten Shadows Technique — shikigami summoning", alias: "The Ten Shadows User" },
  "nobara kugisaki": { hairColor: "auburn orange", hairStyle: "short bob", eyeColor: "orange-brown", gender: "Female", age: "Teenager (16)", role: "Jujutsu Sorcerer", personality: "Confident, Bold, Fashionable", coreTheme: "Urban Supernatural / Magic Realism", accent: "Sassy, confident, loud", wardrobeDetails: "Jujutsu High uniform, nail polish, confident posture", keyProp: "Straw Doll Technique — hammer and nails cursed technique", alias: "The Girl from the Countryside" },
  "ryomen sukuna": { hairColor: "pink / light", hairStyle: "short spiky", eyeColor: "red", gender: "Male", age: "Ancient Immortal (100+)", role: "Supernatural Entity", personality: "Cruel, Sadistic, Arrogant", coreTheme: "Urban Supernatural / Magic Realism", accent: "Deep, menacing, condescending", wardrobeDetails: "four arms, tattoo markings across body, kimono, sharp teeth, extra eyes", keyProp: "Cleave and Dismantle — slashing cursed techniques", alias: "King of Curses" },

  // ── BLEACH ───────────────────────────────────────────────────
  "ichigo kurosaki": { hairColor: "bright orange", hairStyle: "spiky", eyeColor: "brown", gender: "Male", age: "Teenager (15)", role: "Shinigami / Soul Reaper", personality: "Protective, Hot-headed, Brave", coreTheme: "Urban Supernatural / Magic Realism", accent: "Casual, sarcastic, fierce when fighting", wardrobeDetails: "black shinigami shihakusho robes, white obi sash", keyProp: "Zangetsu — massive cleaver-shaped zanpakuto", alias: "Substitute Soul Reaper" },
  "rukia kuchiki": { hairColor: "jet black", hairStyle: "short bob", eyeColor: "violet", gender: "Female", age: "Young Adult (150+)", role: "Shinigami / Soul Reaper", personality: "Serious, Kind, Brave", coreTheme: "Urban Supernatural / Magic Realism", accent: "Formal, composed, occasionally playful", wardrobeDetails: "black shinigami shihakusho robes, white captain haori (later), noble bearing", keyProp: "Sode no Shirayuki — most beautiful ice zanpakuto", alias: "Ice Snow Captain" },
  "sosuke aizen": { hairColor: "chestnut brown", hairStyle: "slicked back", eyeColor: "brown", gender: "Male", age: "Young Adult (unknown, centuries old)", role: "Shinigami / Soul Reaper", personality: "Manipulative, Calm, Genius", coreTheme: "Urban Supernatural / Magic Realism", accent: "Smooth, polite, unsettling calm", wardrobeDetails: "white Arrancar lord robes, or captain haori, intellectual glasses (deception)", keyProp: "Kyoka Suigetsu — perfect hypnosis zanpakuto", alias: "Lord Aizen" },
  "byakuya kuchiki": { hairColor: "jet black", hairStyle: "long straight with kenseikan clips", eyeColor: "dark grey", gender: "Male", age: "Young Adult (centuries old)", role: "Shinigami / Soul Reaper", personality: "Noble, Stoic, Dignified", coreTheme: "Urban Supernatural / Magic Realism", accent: "Formal, aristocratic, measured", wardrobeDetails: "white captain haori over black shihakusho, kenseikan noble hair pieces, silk scarf", keyProp: "Senbonzakura — thousand cherry blossom blade zanpakuto", alias: "Captain of the 6th Division" },

  // ── HUNTER × HUNTER ─────────────────────────────────────────
  "gon freecss": { hairColor: "dark green", hairStyle: "tall spiky", eyeColor: "amber", gender: "Male", age: "Teenager (14)", role: "Hunter", personality: "Cheerful, Adventurous, Naive", coreTheme: "Classic Shounen Fantasy", accent: "Innocent, enthusiastic, direct", wardrobeDetails: "green jacket, green shorts, brown boots, red-tipped spiky hair", keyProp: "Fishing Rod — signature weapon from Whale Island", alias: "The Boy from Whale Island" },
  "killua zoldyck": { hairColor: "platinum silver", hairStyle: "spiky fluffy", eyeColor: "blue", gender: "Male", age: "Teenager (14)", role: "Hunter", personality: "Cool, Intelligent, Loyal", coreTheme: "Classic Shounen Fantasy", accent: "Casual, cocky, occasionally threatening", wardrobeDetails: "purple long-sleeve shirt, grey shorts, sneakers, skateboard", keyProp: "Godspeed — lightning nen technique", alias: "The Assassin Heir" },
  "kurapika": { hairColor: "golden blonde", hairStyle: "short straight", eyeColor: "brown / scarlet (rage)", gender: "Male", age: "Teenager (17)", role: "Hunter", personality: "Intelligent, Vengeful, Determined", coreTheme: "Classic Shounen Fantasy", accent: "Calm, articulate, intense when angry", wardrobeDetails: "blue and gold tabard, white shirt, dark pants, chain accessories", keyProp: "Chain Jail — conjured nen chains for capturing", alias: "The Last Kurta" },
  "hisoka morow": { hairColor: "magenta red", hairStyle: "swept back", eyeColor: "golden", gender: "Male", age: "Young Adult (28)", role: "Hunter", personality: "Sadistic, Playful, Unpredictable", coreTheme: "Classic Shounen Fantasy", accent: "Theatrical, sensual, taunting", wardrobeDetails: "jester-like crop top with card symbols, face paint, star and teardrop markings", keyProp: "Bungee Gum — elastic sticky nen ability", alias: "The Magician" },

  // ── CHAINSAW MAN ────────────────────────────────────────────
  "denji": { hairColor: "dirty blonde", hairStyle: "messy unkempt", eyeColor: "brown / yellow (Chainsaw form)", gender: "Male", age: "Teenager (16)", role: "Demon Slayer", personality: "Simple, Reckless, Honest", coreTheme: "Urban Supernatural / Magic Realism", accent: "Crude, simple, direct", wardrobeDetails: "white shirt, tie, Public Safety uniform, chainsaw cord pull on chest", keyProp: "Chainsaw transformation — chainsaws from head and arms", alias: "Chainsaw Man" },
  "makima": { hairColor: "auburn red", hairStyle: "long braided", eyeColor: "yellow spiral (ringed)", gender: "Female", age: "Young Adult (unknown)", role: "Spy / Agent", personality: "Manipulative, Calm, Mysterious", coreTheme: "Urban Supernatural / Magic Realism", accent: "Soft, eerily calm, commanding", wardrobeDetails: "white dress shirt, black tie, black pants, black shoes, composed posture", keyProp: "Control Devil — power to dominate any being", alias: "The Control Devil" },
  "power": { hairColor: "strawberry blonde (pink)", hairStyle: "long messy with horns", eyeColor: "red / yellow", gender: "Female", age: "Young Adult (unknown)", role: "Demon Slayer", personality: "Chaotic, Arrogant, Childish", coreTheme: "Urban Supernatural / Magic Realism", accent: "Loud, boastful, crude", wardrobeDetails: "Public Safety uniform, horns protruding from head, sharp teeth, messy appearance", keyProp: "Blood Devil powers — creates blood weapons", alias: "The Blood Fiend" },

  // ── SPY × FAMILY ────────────────────────────────────────────
  "loid forger": { hairColor: "golden blonde", hairStyle: "neat parted", eyeColor: "blue", gender: "Male", age: "Young Adult (early 30s)", role: "Spy / Agent", personality: "Calm, Intelligent, Caring", coreTheme: "Slice-of-Life / Retro 90s", accent: "Polite, composed, occasionally flustered", wardrobeDetails: "grey three-piece suit, tie, dress shoes, gloves for missions", keyProp: "Disguise Kit — master of disguises and espionage tools", alias: "Twilight" },
  "yor forger": { hairColor: "jet black", hairStyle: "long with gold hairband", eyeColor: "red", gender: "Female", age: "Young Adult (27)", role: "Assassin", personality: "Kind, Clumsy, Deadly", coreTheme: "Slice-of-Life / Retro 90s", accent: "Gentle, polite, occasionally awkward", wardrobeDetails: "red dress, gold earrings, hairband, assassin outfit underneath, high heels", keyProp: "Gold Stiletto Weapons — concealed throwing daggers", alias: "Thorn Princess" },
  "anya forger": { hairColor: "sakura pink", hairStyle: "short with antenna hair clips", eyeColor: "green", gender: "Female", age: "Child (6)", role: "Student", personality: "Mischievous, Curious, Loving", coreTheme: "Slice-of-Life / Retro 90s", accent: "Childish, excited, catchphrase 'Waku Waku!'", wardrobeDetails: "Eden Academy uniform, black dress, white collar, green star antenna hair clips", keyProp: "Telepathy — ability to read minds", alias: "Starlight Anya" },

  // ── COWBOY BEBOP ─────────────────────────────────────────────
  "spike spiegel": { hairColor: "dark green", hairStyle: "fluffy tousled", eyeColor: "reddish brown (one artificial)", gender: "Male", age: "Young Adult (27)", role: "Bounty Hunter", personality: "Cool, Laid-back, Melancholic", coreTheme: "Futuristic Space Opera", accent: "Casual, dry wit, philosophical", wardrobeDetails: "blue leisure suit, yellow shirt, Lupin-inspired boots, loose tie", keyProp: "Jericho 941 R — customized semi-automatic pistol", alias: "Swimming Bird" },
  "faye valentine": { hairColor: "dark purple", hairStyle: "short choppy", eyeColor: "green", gender: "Female", age: "Young Adult (23, biologically)", role: "Bounty Hunter", personality: "Sarcastic, Independent, Guarded", coreTheme: "Futuristic Space Opera", accent: "Sarcastic, seductive, tough exterior", wardrobeDetails: "yellow hot pants, red crop jacket, white boots, purple headband", keyProp: "Glock 30 — compact semi-automatic handgun", alias: "Romani" },
  "jet black": { hairColor: "jet black", hairStyle: "bald (receding)", eyeColor: "dark", gender: "Male", age: "Prime Adult (36)", role: "Bounty Hunter", personality: "Reliable, Paternal, Gruff", coreTheme: "Futuristic Space Opera", accent: "Deep, gruff, fatherly", wardrobeDetails: "blue flight suit, prosthetic left arm, goatee, muscular build", keyProp: "Walther P99 — standard sidearm", alias: "The Black Dog" },

  // ── EVANGELION ───────────────────────────────────────────────
  "shinji ikari": { hairColor: "dark brown", hairStyle: "short messy", eyeColor: "dark blue", gender: "Male", age: "Teenager (14)", role: "Mecha Pilot", personality: "Timid, Conflicted, Lonely", coreTheme: "Futuristic Space Opera", accent: "Quiet, hesitant, self-doubting", wardrobeDetails: "white shirt, school uniform, or blue and white plugsuit", keyProp: "Evangelion Unit-01 — purple biomechanical mecha", alias: "Third Child" },
  "asuka langley": { hairColor: "fiery orange-red", hairStyle: "long with neural clips", eyeColor: "blue", gender: "Female", age: "Teenager (14)", role: "Mecha Pilot", personality: "Prideful, Aggressive, Insecure", coreTheme: "Futuristic Space Opera", accent: "Loud, abrasive, competitive", wardrobeDetails: "red plugsuit, school uniform, red neural hair clips", keyProp: "Evangelion Unit-02 — red biomechanical mecha", alias: "Second Child" },
  "rei ayanami": { hairColor: "pale blue", hairStyle: "short bob", eyeColor: "red", gender: "Female", age: "Teenager (14)", role: "Mecha Pilot", personality: "Quiet, Stoic, Mysterious", coreTheme: "Futuristic Space Opera", accent: "Monotone, emotionless, minimal words", wardrobeDetails: "white plugsuit, school uniform, bandages (often), pale skin", keyProp: "Evangelion Unit-00 — blue prototype mecha", alias: "First Child" },

  // ── ONE PUNCH MAN ───────────────────────────────────────────
  "saitama": { hairColor: "none (bald)", hairStyle: "bald", eyeColor: "brown", gender: "Male", age: "Young Adult (25)", role: "Pro Hero", personality: "Apathetic, Humble, Lazy", coreTheme: "Classic Shounen Fantasy", accent: "Deadpan, bored, nonchalant", wardrobeDetails: "yellow jumpsuit, red gloves, white cape, red boots, bald head", keyProp: "One Punch — ability to defeat anyone with a single punch", alias: "Caped Baldy" },
  "genos": { hairColor: "golden blonde", hairStyle: "spiky", eyeColor: "gold (mechanical)", gender: "Male", age: "Young Adult (19)", role: "Pro Hero", personality: "Serious, Loyal, Determined", coreTheme: "Classic Shounen Fantasy", accent: "Formal, intense, overly detailed explanations", wardrobeDetails: "mechanical cyborg body, visible gears and vents, black tank top", keyProp: "Incinerate Cannon — arm-mounted flame thrower", alias: "Demon Cyborg" },

  // ── TOKYO GHOUL ─────────────────────────────────────────────
  "ken kaneki": { hairColor: "jet black (later white)", hairStyle: "messy", eyeColor: "grey / red-black (ghoul kakugan)", gender: "Male", age: "Young Adult (19)", role: "Supernatural Entity", personality: "Gentle, Conflicted, Tragic", coreTheme: "Urban Supernatural / Magic Realism", accent: "Soft, thoughtful, occasionally menacing", wardrobeDetails: "black leather combat suit, or casual clothes, half-ghoul mask covering lower face", keyProp: "Kagune — red crystallized predatory organ from back", alias: "The One-Eyed King" },
  "touka kirishima": { hairColor: "dark blue-purple", hairStyle: "short bob with bangs", eyeColor: "blue / red (kakugan)", gender: "Female", age: "Teenager (17)", role: "Supernatural Entity", personality: "Tough, Caring, Short-tempered", coreTheme: "Urban Supernatural / Magic Realism", accent: "Blunt, aggressive, softens around friends", wardrobeDetails: "cafe waitress outfit, or rabbit mask and black battle outfit", keyProp: "Ukaku Kagune — crystallized wing-like ghoul weapon", alias: "Rabbit" },

  // ── SWORD ART ONLINE ────────────────────────────────────────
  "kirito": { hairColor: "jet black", hairStyle: "medium messy", eyeColor: "dark grey", gender: "Male", age: "Teenager (16)", role: "Swordsman / Samurai", personality: "Determined, Loner, Protective", coreTheme: "High Fantasy", accent: "Calm, serious, introspective", wardrobeDetails: "black trenchcoat, black shirt, dark pants, dual wielding swords", keyProp: "Elucidator & Dark Repulser — dual black swords", alias: "The Black Swordsman" },
  "asuna yuuki": { hairColor: "chestnut brown (orange)", hairStyle: "long straight", eyeColor: "amber", gender: "Female", age: "Teenager (17)", role: "Swordsman / Samurai", personality: "Kind, Strong, Determined", coreTheme: "High Fantasy", accent: "Polite, warm, fierce in battle", wardrobeDetails: "white and red Knights of the Blood uniform, rapier at hip", keyProp: "Lambent Light — legendary rapier", alias: "Lightning Flash" },

  // ── CODE GEASS ───────────────────────────────────────────────
  "lelouch lamperouge": { hairColor: "jet black", hairStyle: "straight medium", eyeColor: "violet / red (Geass)", gender: "Male", age: "Teenager (17)", role: "Royalty", personality: "Intelligent, Charismatic, Ruthless", coreTheme: "Military / War Drama", accent: "Commanding, theatrical, eloquent", wardrobeDetails: "Ashford Academy uniform, or Zero's masked costume with cape and helmet", keyProp: "Geass — power of absolute obedience (eye ability)", alias: "Zero" },
  "c.c.": { hairColor: "lime green", hairStyle: "very long straight", eyeColor: "gold", gender: "Female", age: "Ancient Immortal (centuries)", role: "Supernatural Entity", personality: "Aloof, Sarcastic, Mysterious", coreTheme: "Military / War Drama", accent: "Dry, detached, occasionally playful", wardrobeDetails: "white straitjacket outfit, or black pilot suit, Code mark on forehead", keyProp: "Code of Immortality — grants and controls Geass power", alias: "The Immortal Witch" },

  // ── STEINS;GATE ─────────────────────────────────────────────
  "rintaro okabe": { hairColor: "dark brown", hairStyle: "messy unkempt", eyeColor: "dark green", gender: "Male", age: "Young Adult (18)", role: "Scientist / Researcher", personality: "Eccentric, Theatrical, Caring", coreTheme: "Psychological Thriller", accent: "Theatrical, mad scientist persona, dramatic", wardrobeDetails: "white lab coat, green cargo pants, collared shirt", keyProp: "Phone Microwave — time-traveling device made from a microwave", alias: "Hououin Kyouma" },
  "kurisu makise": { hairColor: "chestnut red-brown", hairStyle: "long straight", eyeColor: "violet", gender: "Female", age: "Young Adult (18)", role: "Scientist / Researcher", personality: "Intelligent, Tsundere, Logical", coreTheme: "Psychological Thriller", accent: "Academic, sharp, occasionally flustered", wardrobeDetails: "white dress shirt, red tie, brown jacket, short shorts, knee-high boots", keyProp: "Scientific Papers — published neuroscience thesis", alias: "The Zombie / Christina" },

  // ── RE:ZERO ─────────────────────────────────────────────────
  "subaru natsuki": { hairColor: "jet black", hairStyle: "short messy", eyeColor: "brown", gender: "Male", age: "Teenager (17)", role: "Vanguard Warrior", personality: "Determined, Stubborn, Self-sacrificing", coreTheme: "Isekai / Fantasy World", accent: "Casual, comedic, desperate when stressed", wardrobeDetails: "black and orange tracksuit, butler uniform (later)", keyProp: "Return by Death — ability to revive from death", alias: "The Knight of Emilia" },
  "emilia": { hairColor: "platinum silver", hairStyle: "long flowing", eyeColor: "purple", gender: "Female", age: "Teenager (physically 18)", role: "Royalty", personality: "Kind, Naive, Determined", coreTheme: "Isekai / Fantasy World", accent: "Gentle, polite, earnest", wardrobeDetails: "white and purple dress, crystal hair ornament, pointed ears (half-elf)", keyProp: "Puck — spirit companion (small cat-like familiar)", alias: "The Silver-Haired Half-Elf" },
  "rem": { hairColor: "sky blue", hairStyle: "short with bang over right eye", eyeColor: "light blue", gender: "Female", age: "Teenager (17)", role: "Shrine Maiden / Cleric", personality: "Devoted, Kind, Fierce", coreTheme: "Isekai / Fantasy World", accent: "Polite, humble, passionate", wardrobeDetails: "blue and white maid uniform, hair clip on left side, single horn (demon form)", keyProp: "Morning Star Flail — spiked chain weapon", alias: "The Blue Oni Maid" },

  // ── MOB PSYCHO 100 ──────────────────────────────────────────
  "shigeo kageyama": { hairColor: "jet black", hairStyle: "bowl cut", eyeColor: "dark", gender: "Male", age: "Teenager (14)", role: "Student", personality: "Humble, Kind, Socially awkward", coreTheme: "Academy / School Life", accent: "Quiet, uncertain, monotone", wardrobeDetails: "black school uniform, gakuran style, plain appearance", keyProp: "Psychic Powers — immense telekinetic and psychic abilities", alias: "Mob" },
  "arataka reigen": { hairColor: "dirty blonde", hairStyle: "neat parted", eyeColor: "dark", gender: "Male", age: "Young Adult (28)", role: "Teacher / Mentor", personality: "Charismatic, Deceptive, Caring", coreTheme: "Academy / School Life", accent: "Smooth, confident, fast-talking con-man", wardrobeDetails: "brown business suit, tie, dress shoes, slicked hair", keyProp: "Salt Splash — bucket of purification salt (scam tool)", alias: "Greatest Psychic of the 21st Century" },

  // ── VINLAND SAGA ─────────────────────────────────────────────
  "thorfinn": { hairColor: "dirty blonde", hairStyle: "long messy", eyeColor: "dark blue", gender: "Male", age: "Teenager (17)", role: "Vanguard Warrior", personality: "Vengeful, Determined, Evolving", coreTheme: "Military / War Drama", accent: "Terse, angry, softens over time", wardrobeDetails: "worn leather tunic, fur-lined cloak, Viking-era clothing, scarred", keyProp: "Dual Daggers — inherited from his father", alias: "Karlsefni" },
  "askeladd": { hairColor: "grey-blonde", hairStyle: "medium wavy", eyeColor: "blue", gender: "Male", age: "Prime Adult (40s)", role: "Military Commander", personality: "Cunning, Charismatic, Complex", coreTheme: "Military / War Drama", accent: "Witty, calculating, commanding", wardrobeDetails: "Viking chainmail, fur-lined cloak, leather boots, sword at hip", keyProp: "Short Sword — single-edged Viking blade", alias: "Lucius Artorius Castus" },

  // ── SAILOR MOON ─────────────────────────────────────────────
  "usagi tsukino": { hairColor: "golden blonde", hairStyle: "twin tails with buns (odango)", eyeColor: "blue", gender: "Female", age: "Teenager (14)", role: "Shrine Maiden / Cleric", personality: "Clumsy, Kind, Crybaby", coreTheme: "Urban Supernatural / Magic Realism", accent: "Whiny, dramatic, bubbly", wardrobeDetails: "white sailor suit with blue collar and red bow, tiara, red boots, brooch", keyProp: "Moon Stick — crescent moon-topped wand", alias: "Sailor Moon" },
};

/**
 * Look up structured anime character traits by name.
 * Uses case-insensitive substring matching for flexibility.
 * For example, "luffy" matches "monkey d. luffy".
 */
export function lookupAnimeTraits(name: string): AnimeTraits | null {
  const query = name.toLowerCase().trim();
  
  // 1. Exact match
  if (TRAITS_DB[query]) return { ...TRAITS_DB[query] };
  
  // 2. Check if query is a substring of any key
  for (const [key, traits] of Object.entries(TRAITS_DB)) {
    if (key.includes(query)) return { ...traits };
  }
  
  // 3. Check if any key is a substring of query (e.g. query = "Luffy Monkey D." contains "luffy")
  for (const [key, traits] of Object.entries(TRAITS_DB)) {
    // Split the key into parts and check if any significant part matches
    const keyParts = key.split(/[\s.]+/).filter(p => p.length > 2);
    for (const part of keyParts) {
      if (query.includes(part) && part.length > 3) {
        return { ...traits };
      }
    }
  }
  
  return null;
}
